import { Nunito } from "next/font/google";
import "./globals.css";
// import { useNavigation } from 'next/navigation'; // Importing useNavigation
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/NavBar/NavBar";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Lux Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const navigation = useNavigation(); // Using useNavigation instead of useRouter
  // const hideNavBar = navigation.pathname === '/sign-in' || navigation.pathname === '/sign-up';

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          {/* !hideNavBar &&  <NavBar/>}*/}
          
          <div className='min-h-screen flex flex-col   '>
          {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
