import { Nunito } from "next/font/google";
import "./globals.css";
// import { useNavigation } from 'next/navigation'; // Importing useNavigation
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/NavBar/NavBar";
import Context from "@/components/Context";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Lux Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const navigation = useNavigation(); // Using useNavigation instead of useRouter
  // const hideNavBar = navigation.pathname === '/sign-in' || navigation.pathname === '/sign-up';

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          {/* !hideNavBar &&  <NavBar/>}*/}
          <Context>
          <div className='min-h-screen flex flex-col   '>  
          {children}
          </div>
          </Context>
          <script src="//code.tidio.co/fggbkjmjar5xubslkapfq7zq5kwrsyal.js" async></script>
          <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module" defer></script> 
        </body>
      </html>
    </ClerkProvider>
  );
}
